version: "3.3"
services:
    app:
        build:
            context: ..
            dockerfile: ./docker/app/Dockerfile
        container_name: app
        expose:
            - "8000"
    nginx:
        image: nginx:latest
        container_name: nginx
        ports:
            - "8092:8001"
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ../static:/usr/src/app/static
        depends_on:
            - app